name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      KEYSTATIC_GITHUB_CLIENT_ID: ${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}
      KEYSTATIC_GITHUB_CLIENT_SECRET: ${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}
      KEYSTATIC_SECRET: ${{ secrets.KEYSTATIC_SECRET }}
      PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: "wiener-diarium-keystatic"
      SKIP_KEYSTATIC: true
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install Saxon, ant
        run: |
          sudo apt-get update && sudo apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
          ./scripts/shellscripts/dl_saxon.sh
      - name: Fetch Edition Data
        run: |
          ./scripts/shellscripts/fetch_data.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add attributes
        run: |
          ./scripts/shellscripts/attributes.sh
      # - name: Make ts index
      #   run: |
      #     python ./scripts/python/make_ts_index.py
      - name: Build the site
        run: |
          ant -f ./scripts/ant/build.xml
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: 20

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
